# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bphn9Vxo0cFI3_ZFCrNf0q32rpyFM5pk
"""

#Load libraries
import pandas as pd
import numpy as np
day = pd.read_csv("day.csv")
day.head()
print("\nHeader of the csv file: \n",day.head(),"\n")

#Total missing values
day.isnull().sum()
print("\nNull Values of the csv file: \n",day.isnull().sum(),"\n")

#Imputing Missing Values
#Mean Method
day1 = pd.read_csv("day.csv")
day1.head()
print("\n New Head of the csv file: \n",day1.head(),"\n")

day1.isnull().sum()
print("\nNull Values of the csv file\n",day1.isnull().sum(),"\n")

#Missing values imputed
missing_col = ['yr']
#Using mean to impute the missing values
for i in missing_col:
    day1.loc[day1.loc[:,i].isnull(),i]=day1.loc[:,i].mean()
    day1.isnull().sum()
print("\nNull Values of the csv file\n",day1.isnull().sum(),"\n")

#Median Method
day2 = pd.read_csv("day.csv")
day2.head()
print("\nHeader of the csv file: \n",day.head(),"\n")

day2.isnull().sum()
print("\nNull Values of the csv file: \n",day2.isnull().sum(),"\n")

missing_col_1 = ['yr']
#Using mean to impute the missing values
for i in missing_col_1:
    day2.loc[day2.loc[:,i].isnull(),i] = day2.loc[:,i].median()
    day2.isnull().sum()
print("\nNull Values of the csv file\n",day2.isnull().sum(),"\n")

#Filling with a new category
day2['season'] = day2['season'].fillna('No season')
day2['mnth'] = day2['mnth'].fillna('No mnth')
day2['dteday'] = day2['dteday'].fillna('No dteday')
day2['holiday'] = day2['holiday'].fillna('No holiday')
day2['weekday'] = day2['weekday'].fillna('No weekday')
print("\nNull Values of the csv file: \n",day2.isnull().sum(),"\n")

#Duplicate Values
len(day1)
print("\nLength of the day1 csv file: \n",len(day1),"\n")

day1= day1.drop_duplicates()
len(day1)
print("\nAfter removing duplicates from the day1 csv file:\n Length is : ", len(day1),"\n")

#Missing Values
print(len(day1))

day1 = day1.dropna()
len(day1)
print("\nAfter dropping duplicates from the day1 csv file:\n Length is : ", len(day1),"\n")

#Unnecessary Column
print(day1.head())

day1 = day1.drop(columns=["instant"])
day1.head()
print("Columns after removing 'instant' column: \n", day1.head())