# -*- coding: utf-8 -*-
"""karl_skew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KX2YzftzIsfZ9Ooo9bCh6fpSC9QiV7AA
"""

import numpy as np
def pearson_skewness(data):
  mean =np.mean(data)
  median=np.median(data)
  std_dev=np.std(data)
  skewness=3*(mean-median)/std_dev
  return skewness

x=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 20])
sk=pearson_skewness(x)
print("Person's coefficient of skewness: ", sk)