# -*- coding: utf-8 -*-
"""Measure of Variation_range_IQR_etc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVFjjz-LUYtLx_i_82fXqmviQgmbM6dW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
day = pd.read_csv("/content/day.csv")
day =  day.rename(columns={'Unnamed: 0': 'season'})
day.index = day.season


print(day.head())

#Central Tendency

#mean
day.mean()

day.median()

day.mode()

#Measures of Spread / Dispersion
print(max(day["mnth"]) - min(day["mnth"]))

#Range of mnth
five_num = [day["mnth"].quantile(0),
            day["mnth"].quantile(0.25),
            day["mnth"].quantile(0.50),
            day["mnth"].quantile(0.75),
            day["mnth"].quantile(1)]
print(five_num)

print(day["mnth"].describe())

#Interquartile (IQR) range
print(day["mnth"].quantile(0.75) - day["mnth"].quantile(0.25))

day.boxplot(column="mnth",
               return_type='axes',
               figsize=(8,8))


plt.text(x=0.74, y=22.25, s="3rd Quartile")
plt.text(x=0.8, y=18.75, s="Median")
plt.text(x=0.75, y=15.5, s="1st Quartile")
plt.text(x=0.9, y=10, s="Min")
plt.text(x=0.9, y=33.5, s="Max")
plt.text(x=0.7, y=19.5, s="IQR", rotation=90, size=25)


#Plot graph
plt.show()

#variance
print(day["mnth"].var())

#standard deviation
print(day["mnth"].std())

from numpy import absolute

A = 20
sum_abs_dev = 0  # Initialize absolute deviation sum to 0

# Check if the 'mnth' column exists in the DataFrame
if 'mnth' in day.columns:
    # Absolute deviation calculation
    for i in range(len(day)):
        av = absolute(day["mnth"].iloc[i] - A)
        # Absolute value of the differences of each data point and A
        # Summing all those absolute values
        sum_abs_dev += av

    # finding the mean absolute deviation
    mean_abs_dev = sum_abs_dev / len(day)
    print("\nThe mean absolute deviation of the csv file is: ", mean_abs_dev, "\n")
else:
    print("The 'mnth' column does not exist in the DataFrame.")